## Java의 예외 처리
### 에외(Exception)란?
Java에서 오작동이나 결과에 악영향을 미칠 수 있는 **실행 중 발생한 오류**를 예외(Exception)이라고 한다. <br>
우리가 흔히 아는 컴파일 오류와 예외는 다음과 같은 차이를 가진다.<br>

- #### 컴파일 오류
  문법에 맞지않는 코드를 작성한 경우 발생하는 오류로, 이러한 코드는 사전에 컴파일러에 의해 컴파일 오류로<br>
  걸러지게 된다. 

- #### 예외(Exception)
  예외는 사용자의 잘못된 입력이나, 배열의 인덱스가 해당 배열의 크기를 넘어가는 등, **프로그램 실행 중에**, <br>
  예기치 못한 상황에 의해 발생한다. 
  프로그램 실행 중에 예외가 발생하는 몇 가지 경우를 나열해 보겠다.<br>
  - 정수를 0으로 나눈 경우
  - 배열의 크기보다 큰 인덱스를 이용하여, 해당 배열의 요소에 접근하는 경우
  - 존재하지 않는 파일을 읽으려는 경우
  - 정수 입력을 기다리는 코드가 실행되고 있을 때, 사용자가 문자를 입력한 경우

실행 중에 예외가 발생하면, 자바 플랫폼이 가장 먼저 알게 되어, 현재 실행중인 응용프로그램에게 예외를 전달한다.<br>
만일, **해당 응용프로그램이 예외를 대처하는 코드를 가지고 있지 않다면,** 자바 플랫폼은 해당 응용프로그램을 곧바로 **종료**시킨다.<br>
<br>

### 예외 처리, `try-catch-finally`문
예외처리는 이름 그대로, 프로그램 실행 중 발생하는 예외를 처리(대응) 하는 작업이다. 예외 발생 시, 해당 예외에 알맞게 대응하는<br>
예외처리가 존재한다면, 자바 플랫폼은 해당 프로그램을 종료하지 않는다.<br>

자바에서는 이러한 예외처리 작업을 위해 `try-catch-finally`문을 사용한다.<br>
사용법은 다음과 같다.<br>

```java
try {
  // 예외가 발생할 가능성이 있는 실행문들을 이 try문으로 묶는다. (try 블록)
}
catch (처리할 예외 타입 선언) {
  // catch()문의 ()안에는 처리할 예외의 타입을 선언하고, {}안에는 예외 처리문을 작성한다. (catch 블록)
}
finally {
  // 예외 발생 여부와 상관없이 반드시 마지막에 실행되는 문장이다. 생략 가능함. (finally 블록)
}
```

- ####  `try`블록
  `try` 블록 안에 예외가 발생할 가능성이 있는 실행문들을 묶는다. 

- #### `catch`블록
  `catch()`문의 `()`안에는 처리할 예외의 타입을 선언하고, `{}`안에는 실질적인 예외처리문을 작성한다.<br>
  이때, 주의할 점은 `try`블록에는 예외가 발생할 가능성이 있는 실행문들을 묶어두었지만, **`catch`블록은 예외마다<br>
  하나씩 정의해 주어야 한다.**<br>
  
- #### `finally`블록
  예외발생 여부와는 상관없이 반드시 마지막에 실행되는 문장이다. 생략이 가능하며, 실제로, 많은 경우 생략한다.<br>
<br>



